name: Build and deploy Node.js app to Azure Web App - nextchat (standalone)

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: prod-nextchat
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies (clean)
        run: npm ci

      - name: Build (standalone)
        run: npm run build

      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir -p deploy
          # 拷贝 standalone 产物
          cp -r .next/standalone/* deploy/
          # 拷贝静态资源 (.next/static)
          mkdir -p deploy/.next/static
          cp -r .next/static/* deploy/.next/static/
          # 拷贝 public（如果有）
            if [ -d public ]; then cp -r public deploy/public; fi
          # 可选：复制环境模板或 LICENSE
          echo "==== Deploy folder preview ===="
          find deploy -maxdepth 4 -type f | head -n 60

      - name: Upload deploy artifact
        uses: actions/upload-artifact@v4
        with:
            name: nextchat-standalone
            path: deploy
            if-no-files-found: error
            retention-days: 3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextchat-standalone
          path: deploy

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: nextchat
          slot-name: Production
          package: ./deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0E77F0FAA36C4D8A945D86E0C1342646 }}

      - name: Post deployment info
        run: echo "Standalone build deployed. Make sure Startup Command = 'node server.js'"
